### ISSUE TITLE
Present transaction hashes and blockexplorer links

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/bridge-ui#16]
a button in bridgeUI, with a hoverover state: show transaction/blockexplorer (shown after metaport transferComplete)

approve: 0x1234
transfer: 0x1234
approve wrap: 0x1234
wrap: 0x1234
approve: 0x1234
transfer: 0x1234

popup a window showing a list of all completed transactions, with links to the explorer

**Comment by dmytrotkk** [comment]
resolved by https://github.com/skalenetwork/bridge-ui/pull/42

**Comment by dmytrotkk** [comment]
todo: @SKALE-jace @cstrangedk add a mention of local storage usage in the ToS
