### ISSUE TITLE
Add Nebula chain

### ISSUE THREAD

**Issue by payvint** [skalenetwork/bridge-ui#44]
Add Nebula chain connected to Europa
Add a SKL token possible to transfer between Nebula and Europa

**Comment by TheGreatAxios** [comment]
Chain Information
---
- Add Nebula Chain (green-giddy-denebola)
- Add dApp **Prospectors NFT**
- Current token option is SKL
   - Addresses Include:
      - Europa: 0xE0595a049d02b7674572b0d59cd4880Db60EDC50
      - Europa Wrapped: 0xD162bB5c75FE99144295b03510bAb2DF99617440
      - Nebula: 0x7F73B66d4e6e67bCdeaF277b9962addcDabBFC4d
